//! Error types and runtime error codes for code generation

use eth_ir_data::{BasicBlockId, CasesId, DataId, LargeConstId, LocalId};
use std::{fmt, ops::Range};

/// Runtime error codes for eth-ir generated bytecode
///
/// These are encoded as a single byte in the revert data to signal
/// specific error conditions at runtime. Using a single byte keeps
/// gas costs minimal while providing clear diagnostic information.
///
/// Error codes 0x00-0x7F are reserved for eth-ir runtime errors.
/// Error codes 0x80-0xFF are available for user-defined errors.
pub mod runtime {
    /// Undefined behavior was encountered - the program is in an invalid state
    pub const UNDEFINED_BEHAVIOR: u8 = 0x00;

    /// Non-exhaustive switch without fallback - no case matched
    pub const SWITCH_NO_MATCH: u8 = 0x01;

    /// Invalid internal call - function doesn't exist
    pub const INVALID_INTERNAL_CALL: u8 = 0x02;

    /// Stack depth exceeded in internal calls
    pub const CALL_STACK_OVERFLOW: u8 = 0x03;

    /// Division by zero (if not handled by EVM)
    pub const DIVISION_BY_ZERO: u8 = 0x04;

    /// Array index out of bounds
    pub const INDEX_OUT_OF_BOUNDS: u8 = 0x05;

    /// Memory allocation failed
    pub const MEMORY_ALLOCATION_FAILED: u8 = 0x06;
}

/// Error type for code generation
#[derive(Debug)]
pub enum CodegenError {
    /// Local variable not found in memory layout
    LocalNotFound { local: LocalId },
    /// Data segment not found
    DataSegmentNotFound { segment: DataId },
    /// Invalid block reference
    InvalidBlockReference { block: BasicBlockId },
    /// Invalid cases reference
    InvalidCasesReference { cases: CasesId },
    /// Invalid local range
    InvalidLocalRange { range: Range<usize>, locals_len: usize },
    /// Invalid large constant reference
    InvalidLargeConstReference { constant: LargeConstId },
}

impl fmt::Display for CodegenError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CodegenError::LocalNotFound { local } => {
                write!(f, "Local variable {:?} not found in memory layout", local)
            }
            CodegenError::DataSegmentNotFound { segment } => {
                write!(f, "Data segment {:?} not found", segment)
            }
            CodegenError::InvalidBlockReference { block } => {
                write!(f, "Invalid block reference {:?}", block)
            }
            CodegenError::InvalidCasesReference { cases } => {
                write!(f, "Invalid cases reference {:?}", cases)
            }
            CodegenError::InvalidLocalRange { range, locals_len } => {
                write!(
                    f,
                    "Invalid local range: tried to access locals[{}..{}] but locals.len() is {}",
                    range.start, range.end, locals_len
                )
            }
            CodegenError::InvalidLargeConstReference { constant } => {
                write!(f, "Invalid large constant reference {:?}", constant)
            }
        }
    }
}

impl std::error::Error for CodegenError {}

/// Result type for code generation operations
pub type Result<T> = std::result::Result<T, CodegenError>;
